apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-app
spec:
  revisionHistoryLimit: 5
  replicas: 1
  selector:
    matchLabels:
      app: mlops
  template:
    metadata:
      labels:
        app: mlops
    spec:
      containers:
        - name: mlops-container
          image: ghcr.io/csa20121996/mlops-cats-dogs:initial
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
